wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.14
    start_time: 1665487671
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      2:
      - 1
      - 5
      - 11
      - 49
      4: 3.7.14
      5: 0.12.11
      6: 4.17.0
      8:
      - 5
amp:
  desc: null
  value: true
batch_size:
  desc: null
  value: 64
checkpoint_step:
  desc: null
  value: 100
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 1
eval_step:
  desc: null
  value: 100
hidden_size:
  desc: null
  value: 128
hyper_yaml_path:
  desc: null
  value: ./SSLMemes/config/hyper1.yml
img_feature_path:
  desc: null
  value: ''
learning_rate:
  desc: null
  value: 2.0e-05
model_path:
  desc: null
  value: uclanlp/visualbert-nlvr2-coco-pre
model_type:
  desc: null
  value: visualbert
optimizer:
  desc: null
  value: adam
output_dir:
  desc: null
  value: ./tmp
output_hidden:
  desc: null
  value: 768
random_seed:
  desc: null
  value: 42
resume_training:
  desc: null
  value: false
semi_supervised:
  desc: null
  value: false
train_csv_path:
  desc: null
  value: ./data/splits/random/memotion_train.csv
use_sweep:
  desc: null
  value: false
val_csv_path:
  desc: null
  value: ./data/splits/random/memotion_val.csv
