wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.14
    start_time: 1665459582
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      2:
      - 1
      - 5
      - 11
      - 49
      3:
      - 2
      4: 3.7.14
      5: 0.12.11
      6: 4.17.0
      8:
      - 5
amp:
  desc: null
  value: true
batch_size:
  desc: null
  value: 48
checkpoint_step:
  desc: null
  value: 100
dropout:
  desc: null
  value: 0.5
epoch:
  desc: null
  value: 100
epochs:
  desc: null
  value: 1
eval_step:
  desc: null
  value: 100
hidden_size:
  desc: null
  value: 512
img_feature_path:
  desc: null
  value: data/features/visualbert/
learning_rate:
  desc: null
  value: 0.096224183054845
model_path:
  desc: null
  value: uclanlp/visualbert-nlvr2-coco-pre
model_type:
  desc: null
  value: visualbert
optimizer:
  desc: null
  value: adam
output_dir:
  desc: null
  value: ./tmp
output_hidden:
  desc: null
  value: 768
random_seed:
  desc: null
  value: 42
resume_training:
  desc: null
  value: false
semi_supervised:
  desc: null
  value: false
train_csv_path:
  desc: null
  value: data/splits/random/memotion_train.csv
val_csv_path:
  desc: null
  value: data/splits/random/memotion_val.csv
