method: random
metric:
  goal: maximize
  name: eval_f_score_macro
parameters:
  batch_size:
    distribution: q_log_uniform_values
    max: 80
    min: 32
    q: 8
  dropout:
    values:
    - 0.3
    - 0.4
    - 0.5
  epochs:
    value: 1
  hidden_size:
    values:
    - 128
    - 256
    - 512
  learning_rate:
    distribution: uniform
    max: 0.1
    min: 0
  optimizer:
    values:
    - adam
    - sgd
