wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.14
    start_time: 1665458322
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      4: 3.7.14
      5: 0.12.11
      6: 4.17.0
      8:
      - 5
batch_size:
  desc: null
  value: 120
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 1
hidden_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.07332331301480909
optimizer:
  desc: null
  value: sgd
