wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.14
    start_time: 1665458696
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      2:
      - 1
      - 5
      - 11
      - 49
      3:
      - 2
      4: 3.7.14
      5: 0.12.11
      6: 4.17.0
      8:
      - 5
amp:
  desc: null
  value: true
batch_size:
  desc: null
  value: 136
checkpoint_step:
  desc: null
  value: 100
dropout:
  desc: null
  value: 0.3
encoder_config:
  desc: null
  value: "VisualBertConfig {\n  \"architectures\": [\n    \"VisualBertForPreTraining\"\
    \n  ],\n  \"attention_probs_dropout_prob\": 0.1,\n  \"bos_token_id\": 0,\n  \"\
    bypass_transformer\": false,\n  \"eos_token_id\": 2,\n  \"hidden_act\": \"gelu\"\
    ,\n  \"hidden_dropout_prob\": 0.1,\n  \"hidden_size\": 768,\n  \"initializer_range\"\
    : 0.02,\n  \"intermediate_size\": 3072,\n  \"layer_norm_eps\": 1e-12,\n  \"max_position_embeddings\"\
    : 512,\n  \"model_type\": \"visual_bert\",\n  \"num_attention_heads\": 12,\n \
    \ \"num_hidden_layers\": 12,\n  \"pad_token_id\": 1,\n  \"special_visual_initialize\"\
    : true,\n  \"transformers_version\": \"4.17.0\",\n  \"type_vocab_size\": 2,\n\
    \  \"visual_embedding_dim\": 1024,\n  \"vocab_size\": 30522\n}\n"
epoch:
  desc: null
  value: 100
epochs:
  desc: null
  value: 1
eval_step:
  desc: null
  value: 100
hidden_size:
  desc: null
  value: 256
img_feature_path:
  desc: null
  value: data/features/visualbert/
learning_rate:
  desc: null
  value: 0.006789598146167819
model_path:
  desc: null
  value: uclanlp/visualbert-nlvr2-coco-pre
model_type:
  desc: null
  value: visualbert
optimizer:
  desc: null
  value: sgd
output_dir:
  desc: null
  value: ./tmp
random_seed:
  desc: null
  value: 42
resume_training:
  desc: null
  value: false
semi_supervised:
  desc: null
  value: false
train_csv_path:
  desc: null
  value: data/splits/random/memotion_train.csv
val_csv_path:
  desc: null
  value: data/splits/random/memotion_val.csv
