wandb_version: 1

amp:
  value: true
batch_size:
  value: 80
dropout:
  value: 0.3
epochs:
  value: 1
eval_step:
  value: 100
hidden_size:
  value: 256
img_feature_path:
  value: data/features/visualbert/
learning_rate:
  value: 0.09188388148909347
model_path:
  value: uclanlp/visualbert-nlvr2-coco-pre
model_type:
  value: visualbert
optimizer:
  value: sgd
output_dir:
  value: ./tmp
random_seed:
  value: 42
resume_training:
  value: true
semi-supervised:
  value: true
train_csv_path:
  value: data/splits/random/memotion_train.csv
val_csv_path:
  value: val_csv_path
